
package by.gsu.epamlab.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConverterImpl", targetNamespace = "http://ws.epamlab.gsu.by/", wsdlLocation = "http://localhost:8080/ApacheCXF_SOAP_Service/ConverterService?wsdl")
public class ConverterImpl
    extends Service
{

    private final static URL CONVERTERIMPL_WSDL_LOCATION;
    private final static WebServiceException CONVERTERIMPL_EXCEPTION;
    private final static QName CONVERTERIMPL_QNAME = new QName("http://ws.epamlab.gsu.by/", "ConverterImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ApacheCXF_SOAP_Service/ConverterService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTERIMPL_WSDL_LOCATION = url;
        CONVERTERIMPL_EXCEPTION = e;
    }

    public ConverterImpl() {
        super(__getWsdlLocation(), CONVERTERIMPL_QNAME);
    }

    public ConverterImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTERIMPL_QNAME, features);
    }

    public ConverterImpl(URL wsdlLocation) {
        super(wsdlLocation, CONVERTERIMPL_QNAME);
    }

    public ConverterImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTERIMPL_QNAME, features);
    }

    public ConverterImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConverterImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConverterImplPortType
     */
    @WebEndpoint(name = "ConverterImplPort")
    public ConverterImplPortType getConverterImplPort() {
        return super.getPort(new QName("http://ws.epamlab.gsu.by/", "ConverterImplPort"), ConverterImplPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConverterImplPortType
     */
    @WebEndpoint(name = "ConverterImplPort")
    public ConverterImplPortType getConverterImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.epamlab.gsu.by/", "ConverterImplPort"), ConverterImplPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTERIMPL_EXCEPTION!= null) {
            throw CONVERTERIMPL_EXCEPTION;
        }
        return CONVERTERIMPL_WSDL_LOCATION;
    }

}
